# Generated by Django 3.0 on 2020-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200711_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@gmauil.com', max_length=255, verbose_name='email address'),
        ),
    ]
